extends: default
extends: default
rules:
  line-length:
    max: 120
    level: error
  indentation:
    spaces: 2
    level: error
  trailing-spaces:
    level: error
  empty-lines:
    max: 1
    level: error
  # comments rule was previously disabled to accommodate a one-space formatter.
  # Re-enable default comment checks now that formatting-on-save is fixed.
  document-start:
    present: true
    level: warning
  truthy:
    level: error
