extends: default
rules:
  line-length:
    max: 120
    level: error
  indentation:
    spaces: 2
    level: error
  trailing-spaces:
    level: error
  document-start:
    present: true
    level: warning
  truthy:
    level: error
